apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-web-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/www-web-0

