{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "my-app.fullname" .) }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
{{- end }}

